### ISSUE TITLE
Add scm_breeze to homebrew

### ISSUE THREAD

**Issue by simonweil** [ndbroadbent/scm_breeze#138]
Hi,

Firstly, thank you for a great and useful project!

I requested to add `scm_breeze` to `homebrew` the package manager for OSX.

They replied that they require version release tagging in order to add `scm_breeze` to `homebrew`.

**Would it be possible to do so?** `homebrew` really helps managing software on OSX (I use it for almost all my install software) and I'm sure `scm_breeze` will benefit from being on `homebrew` too by being more widely exposed.

You can view the issue here: homebrew/homebrew#28472

**Comment by milesj** [comment]
+1

**Comment by LM450N** [comment]
This is done no ?

**Comment by ndbroadbent** [comment]
Hey yeah homebrew is great. I'm not what happened here and I don't really have any time to do it myself, but the idea sounds good 👍

**Comment by jeffbyrnes** [comment]
@ndbroadbent looks like they [want a tagged release to use](https://github.com/Homebrew/legacy-homebrew/issues/28472#issuecomment-40713131)
