### ISSUE TITLE
exec_scmb_expand_args in window title

### ISSUE THREAD

**Issue by michaelmior** [ndbroadbent/scm_breeze#149]
My window title ends up prefixed with `exec_scmb_expand_args` when I run my editor. I'm not quite sure why this is this case, but it would be nice if it wasn't. Any help figuring this out would be appreciated :)

**Comment by ComputerDruid** [comment]
$ alias vim
    alias vim='exec_scmb_expand_args /usr/bin/vim'

This lets you do `vim 1` to edit the first result of `gs`

You can of course `unalias vim` to turn this off.

**Comment by michaelmior** [comment]
I already have this alias set up. I'm not sure how this is related to my problem.

**Comment by ComputerDruid** [comment]
"exec_scmb_expand_args in window title"

"exec_scmb_expand_args in alias"

Seems pretty related to me

**Comment by michaelmior** [comment]
Could you explain how this would help solve the problem? I already have the alias set up and it's working fine. However, my terminal was showing exec_scmb_expand_args in the window title, which I didn't want. This seems to be resolved now (and unfortunately I'm not sure why), so I'm closing the issue. However, if you have any further thoughts, maybe some future user would find them helpful.
