### ISSUE TITLE
'll' breaks without ruby installed

### ISSUE THREAD

**Issue by mieky** [ndbroadbent/scm_breeze#165]
In a box without Ruby installed, "ll" fails:

```
$ ll
ls_with_file_shortcuts:42: command not found: ruby
```

It looks like the culprit is some "ruby golf" in the function ls_with_file_shortcuts: https://github.com/ndbroadbent/scm_breeze/blob/master/lib/git/shell_shortcuts.sh#L138

I think the optimal solution would be to get rid of ruby as a hard dependency altogether, the second best to clearly mention ruby as a requirement.

**Comment by tuzonghua** [comment]
I get similar behavior. The rbenv error is because I'm running all my code in Docker, so Ruby isn't installed locally as it were.

```bash
➜  myCode git:(master) ✗ ll
rbenv: version `2.0.0-p643' is not installed
```

**Comment by ndbroadbent** [comment]
Hi, sorry, fixed.
