### ISSUE TITLE
__git_alias:2: no matches found: cmd_args=()

### ISSUE THREAD

**Issue by stephanvane** [ndbroadbent/scm_breeze#168]
Recently I've been getting this message when opening the terminal: 

    Last login: Mon May  4 14:03:07 on ttys004
    __git_alias:2: no matches found: cmd_args=()
    __git_alias:2: no matches found: cmd_args=()
    ➜  ~  

I'd guess it has something to do with this commit: d52ad497bc4c2627027769dc0aaf754afd006021

I'm using scm_breeze with zsh (oh-my-zsh) on osx-Yosemite

**Comment by ndbroadbent** [comment]
@jawshooah - Would you mind taking a look at this? Any idea why this would be happening?

**Comment by hermo** [comment]
I'm experience the same issue with Yosemite and zsh 5.0.7 from homebrew. 
Some commands like gps, gap, gpl etc. stopped working while some like gs worked fine. 

Locally reverting comment d52ad49 fixed the issue for me.

**Comment by jawshooah** [comment]
Strange, everything works fine for me. I'll do some digging when I get home today.

**Comment by g5pw** [comment]
I have a similar issue on Yosemite with ZSH 5.0.7. I found a solution, will send  a pull request later today.

**Comment by jawshooah** [comment]
I think the changes in d52ad49 might be exclusively `bash`-friendly. I'm not familiar with `zsh`, so I'm not sure how to make the changes compatible. @g5pw, did you come to the same conclusion?

**Comment by stephanvane** [comment]
If I tweak your code a bit I can replicate the problem:

```shell
# foo.sh
a () {
  local first_arg="$1"
  local second_arg="$2"
  local third_arg="$3"
  local cmd_args=("${@:4}")
  echo "$first_arg $second_arg $third_arg ${cmd_args[*]}"
}
a foo1 foo2 foo3
```

````shell
➜  ~  ./foo.sh # this one works
foo1 foo2 foo3 

➜  ~  zsh foo.sh # this one doesn't
a:4: no matches found: cmd_args=()

➜  ~  source foo.sh  # same error
a:4: no matches found: cmd_args=()
````

The problem lies in the `local` keyword before `cmd_args=("${@:4}")` (the other 3 `local` keywords don't seem to matter)

**Comment by jawshooah** [comment]
A better solution might be to declare local vars before assigning to them:

```
# foo.sh
foo () {
  local first_arg; local second_arg; local third_arg; local cmd_args
  first_arg="$1"
  second_arg="$2"
  third_arg="$3"
  cmd_args=("${@:4}")
  echo "$first_arg $second_arg $third_arg ${cmd_args[*]}"
}
foo "$@"
```

```
$ sh foo.sh foo1 foo2 foo3
foo1 foo2 foo3

$ zsh /tmp/foo.sh foo1 foo2 foo3
foo1 foo2 foo3

$ zsh -c 'source /tmp/foo.sh; foo foo1 foo2 foo3'

foo1 foo2 foo3
```

**Comment by g5pw** [comment]
My solution was actually not correct :D But it looks like @jawshooah might be the winner, his solution works for me!

**Comment by stephanvane** [comment]
You're right @jawshooah, that seems to be the best solution. I created a pull-request (e9217f50ab0a0c6fa13e8989a87814ac5befe98c)

**Comment by jawshooah** [comment]
I see your commit, but no pull request. Are you sure you created one?

**Comment by stephanvane** [comment]
Right again @jawshooah, guess I missed a step somewhere (or assumed that Github would add a PR along with the commit). Created one now.

Thank you all for the quick thinking! I learned a lesson of two on the bash/zsh scripting area. Keep up the good work!

**Comment by ndbroadbent** [comment]
Thanks all, merged the fix
