### ISSUE TITLE
Aliases for 'git fetch' and 'git checkout' broken

### ISSUE THREAD

**Issue by stephanvane** [ndbroadbent/scm_breeze#176]
The latest pull request (#175) seems to have broken #174 again. I'm using oh-my-zsh: `zsh 5.0.5 (x86_64-apple-darwin14.0)`

```zsh
➜  ~  which gco
gco: aliased to git checkout checkout
```

The previous version: (d288f3cd74cfc01fcb0caf96b9817ddcc4450a67) worked perfectly for me (in zsh). While the zsh-specific fix in #175 seems to break it again. Maybe the author of this fix uses an other / older zsh version?
@armen, could you please comment on this? What is your output for `which gco` when using the newest version (6183ba963ef37f31d02b9de51ba810fd762917e1). Also, what version of zsh are you using?

**Comment by armen** [comment]
I'm using old version of zsh.

```
which gco
gco='git checkout'
        /usr/bin/git
```

```
zsh --version
zsh 4.3.10 (x86_64-redhat-linux-gnu)
```

**Comment by armen** [comment]
@stephanvane could you please run following tests in your zsh:

```
#/bin/env zsh

function t {
    echo ${@:4}
    echo $@
}

t one two three four five
```
```
./test-zsh.sh
four five
one two three four five
```

And:

```
#/bin/env bash

function t {
    echo ${@:4}
    echo $@
}

t one two three four five
```

```
./test-bash.sh
four five
one two three four five
```

**Comment by stephanvane** [comment]
sure:

```zsh
➜  ~  ./test-zsh.sh 
four five
one two three four five
➜  ~  ./test-bash.sh 
four five
one two three four five
```

**Comment by armen** [comment]
That confirms the bug I have in my system should be somewhere else and has nothing to do with the slicing.

**Comment by stephanvane** [comment]
Hmm, I'm afraid I don't understand it fully. In the comments [here](https://github.com/ndbroadbent/scm_breeze/commit/1ef06aa9cdc7bbd01bb3f92dcf1e61d7cd9b2576) you said the output of 
```zsh
#!/bin/zsh
mytest() {
    echo ${@:3}
}
mytest one two three four
```
was `four`.

On my system the output would be `three four`. This confirms that the problem on your system *does* have something to do with slicing right?

**Comment by armen** [comment]
My confusion was for the fact that in the above test I forgot the bang after the sha, If you see the first line of my test instead of #! it is # that means both are executed with *sh*.

Yeah the bug still caused by the slicing. now I have another alternative. Could you please try this.


```
#!/bin/env zsh
mytest() {
    shift 2
    echo $@
}
mytest one two three four
```

**Comment by stephanvane** [comment]
Good catch. We're on the right track
```zsh
#!/bin/env zsh
mytest() {
    shift 2
    echo $@
}
mytest one two three four
```

```zsh
➜  ~  ./test-zsh.sh 
three four
```

**Comment by armen** [comment]
Cool, I'll send another pull request I hope it wont break anything this time.

**Comment by armen** [comment]
@stephanvane Could you please check the pull request and see if it fixes the problem?

**Comment by stephanvane** [comment]
seems to work:

```zsh
➜  ~  which gco
gco: aliased to git checkout
```

**Comment by armen** [comment]
cool, thanks.

**Comment by ndbroadbent** [comment]
Thanks!

**Comment by stephanvane** [comment]
Thanks all, 
Good job
