### ISSUE TITLE
Integrate diff-so-fancy

### ISSUE THREAD

**Issue by rebolyte** [ndbroadbent/scm_breeze#207]
Is there a way to integrate [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) with scm_breeze's numbered shortcuts? I was able to add an alias that diff'd the whole repo, but I couldn't get numbered shortcuts to work.

**Comment by ghthor** [comment]
From my initial inspection, `diff-so-fancy` is only used as a pipe target for output from a diffing tool. If this is incorrect, can you give me an example of how you'd use it with numbered shortcuts?

I was able to use `g diff --color 1 | diff-so-fancy` and it worked as expected. It'd be nice to use `gd 1 | diff-so-fancy` or integrate `diff-so-fancy` into the `gd` alias to enable `gd 1` to output through `diff-so-fancy`. This should of course be configurable, maybe as an option, `git_diff_post_processing_tool` or something of that nature. I'm looking into how this option could be added.

**Comment by ghthor** [comment]
I was able to make `diff-so-fancy` the default output of `gd 1` by setting it in my global gitconfig[1] file.

```
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
```

I propose that this is the best way to enable DSF and nothing should be changed/added to scm_breeze.

[1] https://github.com/so-fancy/diff-so-fancy#usage

**Comment by rebolyte** [comment]
Great, thank you! I wasn't thinking it would be integrated into scm_breeze, so this is just what I was looking for.
