### ISSUE TITLE
-bash: gb: command not found

### ISSUE THREAD

**Issue by joaovpmamede** [ndbroadbent/scm_breeze#93]
I'm running on OSX and I'm getting this message.
Every shortcut that deals with branch seems to not be working.

**Comment by darwin** [comment]
Double check your own aliases (defined after scm_breeze script is run). I was getting the same message for "gh" which happened to be defined as my own alias.

**Comment by joaovpmamede** [comment]
@darwin that's right. I should've closed this issue as I've got it working moments after.

Thank you anyway.
